/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as siteLayoutRouteRouteImport } from './routes/(site)/_layout/route'
import { Route as legalLayoutRouteRouteImport } from './routes/(legal)/_layout/route'
import { Route as siteLayoutIndexRouteImport } from './routes/(site)/_layout/index'
import { Route as siteLayoutPricingRouteImport } from './routes/(site)/_layout/pricing'
import { Route as siteLayoutBlogRouteImport } from './routes/(site)/_layout/blog'
import { Route as legalLayoutTermsRouteImport } from './routes/(legal)/_layout/terms'
import { Route as legalLayoutPrivacyRouteImport } from './routes/(legal)/_layout/privacy'

const siteLayoutRouteRoute = siteLayoutRouteRouteImport.update({
  id: '/(site)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const legalLayoutRouteRoute = legalLayoutRouteRouteImport.update({
  id: '/(legal)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const siteLayoutIndexRoute = siteLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => siteLayoutRouteRoute,
} as any)
const siteLayoutPricingRoute = siteLayoutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => siteLayoutRouteRoute,
} as any)
const siteLayoutBlogRoute = siteLayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => siteLayoutRouteRoute,
} as any)
const legalLayoutTermsRoute = legalLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => legalLayoutRouteRoute,
} as any)
const legalLayoutPrivacyRoute = legalLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => legalLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof legalLayoutPrivacyRoute
  '/terms': typeof legalLayoutTermsRoute
  '/blog': typeof siteLayoutBlogRoute
  '/pricing': typeof siteLayoutPricingRoute
  '/': typeof siteLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof legalLayoutPrivacyRoute
  '/terms': typeof legalLayoutTermsRoute
  '/blog': typeof siteLayoutBlogRoute
  '/pricing': typeof siteLayoutPricingRoute
  '/': typeof siteLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(legal)/_layout': typeof legalLayoutRouteRouteWithChildren
  '/(site)/_layout': typeof siteLayoutRouteRouteWithChildren
  '/(legal)/_layout/privacy': typeof legalLayoutPrivacyRoute
  '/(legal)/_layout/terms': typeof legalLayoutTermsRoute
  '/(site)/_layout/blog': typeof siteLayoutBlogRoute
  '/(site)/_layout/pricing': typeof siteLayoutPricingRoute
  '/(site)/_layout/': typeof siteLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/privacy' | '/terms' | '/blog' | '/pricing' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/privacy' | '/terms' | '/blog' | '/pricing' | '/'
  id:
    | '__root__'
    | '/(legal)/_layout'
    | '/(site)/_layout'
    | '/(legal)/_layout/privacy'
    | '/(legal)/_layout/terms'
    | '/(site)/_layout/blog'
    | '/(site)/_layout/pricing'
    | '/(site)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  legalLayoutRouteRoute: typeof legalLayoutRouteRouteWithChildren
  siteLayoutRouteRoute: typeof siteLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(site)/_layout': {
      id: '/(site)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/_layout': {
      id: '/(legal)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legalLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/_layout/': {
      id: '/(site)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof siteLayoutIndexRouteImport
      parentRoute: typeof siteLayoutRouteRoute
    }
    '/(site)/_layout/pricing': {
      id: '/(site)/_layout/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof siteLayoutPricingRouteImport
      parentRoute: typeof siteLayoutRouteRoute
    }
    '/(site)/_layout/blog': {
      id: '/(site)/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof siteLayoutBlogRouteImport
      parentRoute: typeof siteLayoutRouteRoute
    }
    '/(legal)/_layout/terms': {
      id: '/(legal)/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalLayoutTermsRouteImport
      parentRoute: typeof legalLayoutRouteRoute
    }
    '/(legal)/_layout/privacy': {
      id: '/(legal)/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalLayoutPrivacyRouteImport
      parentRoute: typeof legalLayoutRouteRoute
    }
  }
}

interface legalLayoutRouteRouteChildren {
  legalLayoutPrivacyRoute: typeof legalLayoutPrivacyRoute
  legalLayoutTermsRoute: typeof legalLayoutTermsRoute
}

const legalLayoutRouteRouteChildren: legalLayoutRouteRouteChildren = {
  legalLayoutPrivacyRoute: legalLayoutPrivacyRoute,
  legalLayoutTermsRoute: legalLayoutTermsRoute,
}

const legalLayoutRouteRouteWithChildren =
  legalLayoutRouteRoute._addFileChildren(legalLayoutRouteRouteChildren)

interface siteLayoutRouteRouteChildren {
  siteLayoutBlogRoute: typeof siteLayoutBlogRoute
  siteLayoutPricingRoute: typeof siteLayoutPricingRoute
  siteLayoutIndexRoute: typeof siteLayoutIndexRoute
}

const siteLayoutRouteRouteChildren: siteLayoutRouteRouteChildren = {
  siteLayoutBlogRoute: siteLayoutBlogRoute,
  siteLayoutPricingRoute: siteLayoutPricingRoute,
  siteLayoutIndexRoute: siteLayoutIndexRoute,
}

const siteLayoutRouteRouteWithChildren = siteLayoutRouteRoute._addFileChildren(
  siteLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  legalLayoutRouteRoute: legalLayoutRouteRouteWithChildren,
  siteLayoutRouteRoute: siteLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
